### ISSUE TITLE
Hover feature for the arrow button

### ISSUE THREAD

**Issue by prakhar-1005** [Ankit-11525/e-commerce_redstore.github.io#102]
The arrow button does not have hover feature.

 I would like to add it to increase site responsiveness and enhance the user experience.

Screenshots:
![Screenshot (46)_LI](https://user-images.githubusercontent.com/94559623/194768322-66e19fbf-2dff-49d8-9341-29de6e5dc40e.jpg)

**Comment by SandeshGC** [comment]
I have one more idea that can make the arrow button better.

The arrow button should be visible only when the user scrolls down from the hero section of any page. 
Currently the button is present only in the Home page. It should also be available on the products page for now (because there's no about page)

**Comment by DhruvDhari** [comment]
i have given it an hover effect

**Comment by prakhar-1005** [comment]
But there is no zoom effect on the button

**Comment by prakhar-1005** [comment]
Hey @Ankit-11525 please review my issue

**Comment by SandeshGC** [comment]
Hey @prakhar-1005 , you can work on this issue, once @Ankit-11525 can access his laptop he will assign you.

**Comment by anmolranjan1** [comment]
Hey @Ankit-11525, Please assign me this issue. I am familiar with these.
